name = "dinnerboard"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "DINNERBOARD"
id = "d2dc84d2d362401184b44503a88aae87"

# Set AUTH_TOKEN as a secret, not here:
# wrangler secret put AUTH_TOKEN